// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9aN1Bgvt0_VtRx-Qd0H4K7HFsAsvVm9U',
    appId: '1:453315723857:web:b07dbbf89a2cbf31456e70',
    messagingSenderId: '453315723857',
    projectId: 'smart-tutor-6f2fe',
    authDomain: 'smart-tutor-6f2fe.firebaseapp.com',
    storageBucket: 'smart-tutor-6f2fe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6FgSM7TiR89GIUP3mehPgKUYovKlr-ME',
    appId: '1:453315723857:android:0f2b65b596329107456e70',
    messagingSenderId: '453315723857',
    projectId: 'smart-tutor-6f2fe',
    storageBucket: 'smart-tutor-6f2fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo1Ii-9C-wIrFCVAW6SftAhT5nMFWlM7c',
    appId: '1:453315723857:ios:d7a7ca9b1d312d88456e70',
    messagingSenderId: '453315723857',
    projectId: 'smart-tutor-6f2fe',
    storageBucket: 'smart-tutor-6f2fe.firebasestorage.app',
    iosBundleId: 'com.example.smartTutor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo1Ii-9C-wIrFCVAW6SftAhT5nMFWlM7c',
    appId: '1:453315723857:ios:d7a7ca9b1d312d88456e70',
    messagingSenderId: '453315723857',
    projectId: 'smart-tutor-6f2fe',
    storageBucket: 'smart-tutor-6f2fe.firebasestorage.app',
    iosBundleId: 'com.example.smartTutor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9aN1Bgvt0_VtRx-Qd0H4K7HFsAsvVm9U',
    appId: '1:453315723857:web:3967d221ec696d0b456e70',
    messagingSenderId: '453315723857',
    projectId: 'smart-tutor-6f2fe',
    authDomain: 'smart-tutor-6f2fe.firebaseapp.com',
    storageBucket: 'smart-tutor-6f2fe.firebasestorage.app',
  );
}
